# Generated by Django 4.2.17 on 2025-01-03 17:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nif', models.CharField(max_length=9)),
                ('CC', models.CharField(max_length=13)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='processoclinico.pessoa')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
            bases=('processoclinico.pessoa',),
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='processoclinico.pessoa')),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=20)),
                ('morada', models.CharField(max_length=255)),
                ('telemovel', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            bases=('processoclinico.pessoa',),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('receitas', models.ManyToManyField(blank=True, related_name='consultas', to='processoclinico.receita')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processoclinico.agente')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processoclinico.utente')),
            ],
        ),
    ]
