# Generated by Django 5.0.1 on 2025-01-16 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processoclinico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('s_min', models.CharField(default=uuid.uuid4, editable=False, max_length=36)),
                ('s_max', models.CharField(default=uuid.uuid4, editable=False, max_length=36)),
                ('s_total', models.CharField(default=uuid.uuid4, editable=False, max_length=36)),
                ('fornecedor', models.CharField(max_length=100)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processoclinico.medicamento')),
            ],
        ),
    ]
