# Generated by Django 5.0.1 on 2025-01-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processoclinico', '0002_medicamento_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='CC',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='nif',
        ),
        migrations.AlterField(
            model_name='stock',
            name='s_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='s_min',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='s_total',
            field=models.IntegerField(),
        ),
    ]
