# Generated by Django 5.0.1 on 2025-01-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processoclinico', '0005_alter_pessoa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='medicamentos',
            field=models.ManyToManyField(blank=True, related_name='receitas', to='processoclinico.medicamento'),
        ),
    ]
