# Generated by Django 5.0.1 on 2025-01-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processoclinico', '0006_receita_medicamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='data_hora',
        ),
    ]
