# Generated by Django 5.0.1 on 2025-01-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processoclinico', '0007_remove_receita_data_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='stock',
            name='fornecedores',
            field=models.ManyToManyField(related_name='stocks', to='processoclinico.fornecedor'),
        ),
    ]
